# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sys.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sys.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tsys.proto\"B\n\x0bTimeRequest\x12\x0f\n\x07good_id\x18\x01 \x01(\x05\x12\x11\n\ttimeStart\x18\x02 \x01(\t\x12\x0f\n\x07timeEnd\x18\x03 \x01(\t\"D\n\tpriceInfo\x12\x11\n\tmax_price\x18\x01 \x01(\x05\x12\x11\n\tmin_price\x18\x02 \x01(\x05\x12\x11\n\tavg_price\x18\x03 \x01(\x05\"\x1d\n\nSalesQuest\x12\x0f\n\x07good_id\x18\x01 \x01(\x05\"D\n\tsalesInfo\x12\x11\n\tsale_best\x18\x01 \x01(\t\x12\x12\n\nsale_worst\x18\x02 \x01(\t\x12\x10\n\x08snippets\x18\x03 \x03(\t2c\n\x0bShopService\x12*\n\x0cPricesNumber\x12\x0c.TimeRequest\x1a\n.priceInfo\"\x00\x12(\n\x0bSalesNUmber\x12\x0b.SalesQuest\x1a\n.salesInfo\"\x00\x62\x06proto3')
)




_TIMEREQUEST = _descriptor.Descriptor(
  name='TimeRequest',
  full_name='TimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='good_id', full_name='TimeRequest.good_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStart', full_name='TimeRequest.timeStart', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeEnd', full_name='TimeRequest.timeEnd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=79,
)


_PRICEINFO = _descriptor.Descriptor(
  name='priceInfo',
  full_name='priceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_price', full_name='priceInfo.max_price', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_price', full_name='priceInfo.min_price', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avg_price', full_name='priceInfo.avg_price', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=149,
)


_SALESQUEST = _descriptor.Descriptor(
  name='SalesQuest',
  full_name='SalesQuest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='good_id', full_name='SalesQuest.good_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=180,
)


_SALESINFO = _descriptor.Descriptor(
  name='salesInfo',
  full_name='salesInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sale_best', full_name='salesInfo.sale_best', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sale_worst', full_name='salesInfo.sale_worst', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snippets', full_name='salesInfo.snippets', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=250,
)

DESCRIPTOR.message_types_by_name['TimeRequest'] = _TIMEREQUEST
DESCRIPTOR.message_types_by_name['priceInfo'] = _PRICEINFO
DESCRIPTOR.message_types_by_name['SalesQuest'] = _SALESQUEST
DESCRIPTOR.message_types_by_name['salesInfo'] = _SALESINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeRequest = _reflection.GeneratedProtocolMessageType('TimeRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMEREQUEST,
  __module__ = 'sys_pb2'
  # @@protoc_insertion_point(class_scope:TimeRequest)
  ))
_sym_db.RegisterMessage(TimeRequest)

priceInfo = _reflection.GeneratedProtocolMessageType('priceInfo', (_message.Message,), dict(
  DESCRIPTOR = _PRICEINFO,
  __module__ = 'sys_pb2'
  # @@protoc_insertion_point(class_scope:priceInfo)
  ))
_sym_db.RegisterMessage(priceInfo)

SalesQuest = _reflection.GeneratedProtocolMessageType('SalesQuest', (_message.Message,), dict(
  DESCRIPTOR = _SALESQUEST,
  __module__ = 'sys_pb2'
  # @@protoc_insertion_point(class_scope:SalesQuest)
  ))
_sym_db.RegisterMessage(SalesQuest)

salesInfo = _reflection.GeneratedProtocolMessageType('salesInfo', (_message.Message,), dict(
  DESCRIPTOR = _SALESINFO,
  __module__ = 'sys_pb2'
  # @@protoc_insertion_point(class_scope:salesInfo)
  ))
_sym_db.RegisterMessage(salesInfo)



_SHOPSERVICE = _descriptor.ServiceDescriptor(
  name='ShopService',
  full_name='ShopService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=252,
  serialized_end=351,
  methods=[
  _descriptor.MethodDescriptor(
    name='PricesNumber',
    full_name='ShopService.PricesNumber',
    index=0,
    containing_service=None,
    input_type=_TIMEREQUEST,
    output_type=_PRICEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SalesNUmber',
    full_name='ShopService.SalesNUmber',
    index=1,
    containing_service=None,
    input_type=_SALESQUEST,
    output_type=_SALESINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOPSERVICE)

DESCRIPTOR.services_by_name['ShopService'] = _SHOPSERVICE

# @@protoc_insertion_point(module_scope)
