# Generated by Django 2.0.5 on 2020-05-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField(default=0)),
                ('sell_time', models.DateTimeField(verbose_name='good sell time')),
                ('sell_price', models.IntegerField(default=0)),
                ('deal_price', models.IntegerField(default=0)),
            ],
        ),
    ]
